version: "2"
services:

  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - PHP_IDE_CONFIG="serverName=docker-server"
      - XDEBUG_CONFIG="remote_enable=1 remote_mode=req remote_host=172.17.0.1 remote_port=9000 remote_connect_back=0"
    ports:
      - "80:80"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    volumes:
    - .:/var/www
